language: php

branches:
  only:
    - master
    - devel

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - MAGENTO_VERSION="magento-mirror-1.4.2.0"
  - MAGENTO_VERSION="magento-mirror-1.5.1.0"
  - MAGENTO_VERSION="magento-mirror-1.6.2.0"
  - MAGENTO_VERSION="magento-mirror-1.7.0.2"
  - MAGENTO_VERSION="magento-mirror-1.8.1.0"
  - MAGENTO_VERSION="magento-mirror-1.9.1.1"
  - MAGENTO_VERSION="magento-mirror-1.9.2.2"

matrix:
  fast_finish: true
  exclude:
    # Newer Magento versions use newer PHP versions
    - php: 5.3
      env: MAGENTO_VERSION="magento-mirror-1.9.1.1"

    - php: 5.3
      env: MAGENTO_VERSION="magento-mirror-1.9.2.2"

    # Old Magento versions are not officially supported to run with PHP 5.5
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.4.2.0"

    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.5.1.0"

    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"

    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"

before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS `magento_travis`;'
- wget http://files.magerun.net/n98-magerun-latest.phar -O n98-magerun.phar
- chmod +x ./n98-magerun.phar
- ./n98-magerun.phar install --magentoVersionByName="${MAGENTO_VERSION}" --installationFolder="./${MAGENTO_VERSION}" --dbHost=localhost --dbUser=root --dbPass='' --dbName="magento_travis" --installSampleData=no --useDefaultConfigParams=yes --baseUrl="http://travis.magento.local/"
- export MAGE="./${MAGENTO_VERSION}/app/Mage.php"

script : phpunit -c phpunit.xml.travis
